### ISSUE TITLE
UK VAT Precision during calculations

### ISSUE THREAD

**Issue by Laserbase** [elixirmoney/money#107]
Hi

Is this a problem meeting legal requirements for invoices/ VAT Returns ?

Having a different precision between store and to_string would get close to fixing the problem.

# From:
https://www.gov.uk/guidance/vat-guide-notice-700

# Note:
Other jurisdictions are available such as GST in Australia, I'm sure the it will not be only the UK that has this or similar legally binding rules.

# Quote
```
17.5.2 Calculation based on tax per unit or per article
If you want to work out the VAT per unit or per article
    (for example, for use in price lists), 
    you must work out the amounts in one of the following ways:

4 digits after the decimal point and then round to 3 digits 
- for example, if the VAT is £0.0024, it should be rounded to £0.002 (0.2p)

the nearest 1p or 0.5p 
- if you decide to do this, 
    you must not round the VAT down to ‘nil’ on any unit or article 
    that is liable at the standard or reduced rate, 
    for example, if the VAT is £0.0024 it should be rounded to £0.005 (0.5p)

```

**Comment by Nitrino** [comment]
Hi @Laserbase. 

Could you please clarify, do you need to store currencies with custom exponent or support for rounding rules?

**Comment by Laserbase** [comment]
+Hi

I think this is more than a simple hack.

Notice that the procedure as described by the VAT documents is more for parchment and quill than an automated system.

I'll fork this and investigate further and submit a pull/merge request when I have an idea of global practice.
