### ISSUE TITLE
Surprising operands

### ISSUE THREAD

**Issue by svarlet** [elixirmoney/money#109]
Hi,

Thanks for the great work shared with the community.

While I was reading the readme, I got a little bit surprised by this in particular:
```
five_eur              = Money.new(500, :EUR)
ninety_nine_eur  = Money.subtract(hundred_eur, 1)   # %Money{amount: 99_00, currency: :EUR}
```

Can you explain the choice of using 500 to represent an actual value of 5 and at the same time using 1 to represent an actual value of 1? Or with code, why not?
```
ninety_nine_eur  = Money.subtract(hundred_eur, **100**)   # %Money{amount: 99_00, currency: :EUR}
```

Thanks for the clarification,
Seb

**Comment by voughtdq** [comment]
It's probably a typo:

```elixir
five_eur = Money.new(500, :EUR); five_eur
ten_eur = Money.add(five_eur, five_eur); ten_eur
hundred_eur = Money.multiply(ten_eur, 10); hundred_eur
ninety_nine_eur = Money.subtract(hundred_eur, 1); ninety_nine_eur
shares = Money.divide(ninety_nine_eur, 2); shares
```

This is the output in iex:
![money_screenshot](https://user-images.githubusercontent.com/1967287/62009497-da8f9b80-b12d-11e9-9037-eb9c5cbac8f5.png)

**Comment by Nitrino** [comment]
@svarlet @voughtdq Good catch. Thanks, I'm fixed readme. 🔥
