### ISSUE TITLE
Easy way to do a basic operation on a List of Moneys

### ISSUE THREAD

**Issue by nicolasblanco** [elixirmoney/money#117]
Hello,
I'm sorry to ask a question on the Issues of the project, but I'm very often doing a basic operation on a list of Money elements, for example sum a List of Money elements. Right now I'm almost always writing utilities functions like this:
```
  def sum_moneys(moneys) do
    moneys
    |> Enum.reduce(Money.new(0), fn price, acc -> Money.add(acc, price) end)
  end
```

I'm wondering if this is the best way to do, and if it is common enough so that at some point, it would be possible to integrate directly in the library.

**Comment by andrewtimberlake** [comment]
This is as simple as:
```elixir
moneys = [Money.new(10), Money.new(20), Money.new(30)]
Enum.reduce(moneys, &Money.add/2)
```
