### ISSUE TITLE
Implementing from_decimal and to_decimal

### ISSUE THREAD

**Issue by strzibny** [elixirmoney/money#120]
I think it would be nice and beneficial if there could be a way to accept `Decimal` on both input and provide on the output side. Many applications might be working or getting decimals and if then we want to use the money library it's kind of cumbersome. What do you think?

**Comment by Nitrino** [comment]
Hi @strzibny,

I think this is a great idea.
For input values, I think we can expand the capabilities of the `parse` function, now supported strings and floats.

Workaround for current functionality:
```elixir
iex(7)> Decimal.cast(2.5) |> Decimal.to_float() |> Money.parse!()
%Money{amount: 250, currency: :USD}
```
I think` to_decimal` is a good name for the conversion function.

If you want to contribute, pull requests are welcome.

**Comment by strzibny** [comment]
Do you think that something like the following is fine for the reverse?

```
money_str = Money.to_string(money, separator: "", delimiter: ".", symbol: false)
{:ok, decimal} = Decimal.parse(money_str)
```

**Comment by Nitrino** [comment]
It's a working option, but it's better to work with numbers.

```elixir
iex(17)> price = Money.new(25, :USD)
%Money{amount: 25, currency: :USD}
iex(18)> price_in_float = price.amount / Money.Currency.sub_units_count!(price)
0.25
iex(19)> Decimal.from_float(price_in_float)
#Decimal<0.25>
```

This will give the same result, but it will avoid unnecessary conversions and the math will not depend on formatting settings.

**Comment by strzibny** [comment]
@Nitrino yes, that would work better :)
