### ISSUE TITLE
Question: Can this library represent money internally with a decimal type is it limited to integers?

### ISSUE THREAD

**Issue by robotarmy** [elixirmoney/money#123]
Hi!

I'm wondering if it is possible to switch the underlying datatype to something "financial" safe like decimal type ( ie decimal(6) for representing very large or small currencies ) without compounding fraction of dollar errors like float (arbitrary precision) or integer ( narrow precision)

**Comment by Nitrino** [comment]
Hi @robotarmy 
We use an integer under the hood. Replacing it with decimal will be a non-trivial task.
We have a decimal conversion(`Money.to_decimal`), but I think this is not enough for you.

Perhaps in your case, this library is better suited
https://github.com/kipcole9/money

**Comment by robotarmy** [comment]
thank you1
