### ISSUE TITLE
Using Money.Ecto.Amount.Type in embedded schema

### ISSUE THREAD

**Issue by teamon** [elixirmoney/money#126]
When using `Money.Ecto.Amount.Type` in embedded schema like this:

```elixir
defmodule Outer do
  schema "outers" do
    embeds_many :inners, Inner
  end
end

defmodule Inner do
  embedded_schema do
    field :price, Money.Ecto.Amount.Type
  end
end
```
with `outers.inners` backed by a json database column it results with an error: 

```
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Money{amount: 1500, currency: :USD} of type Money (a struct), Jason.Encoder protocol must always be explicitly implemented.
```

Implementing `Jason.Encoder` is straightforward (`Protocol.derive(Jason.Encoder, Money)`) but results in `{"price": {"amount": 123, "currency": "XYZ"}}` json object stored in database, which is not what the `Money.Ecto.Amount.Type` is supposed to do (which is to store only the amount as integer).

This is due to a fact that embedded schemas [do not go through regular casting phase](https://hexdocs.pm/ecto/Ecto.Schema.html#embeds_one/3-encoding-and-decoding):

> For example, PostgreSQL will store embeds on top of JSONB columns, which means types in embedded schemas won't go through the usual dump->DB->load cycle but rather encode->DB->decode->cast. This means that, when using embedded schemas with databases like PG or MySQL, make sure all of your types can be JSON encoded/decoded correctly. Ecto provides this guarantee for all built-in types.

However, I've found out that this is not 100% true, as one can use [`Ecto.Type`'s `c:embed_as/1`](https://hexdocs.pm/ecto/Ecto.Type.html#c:embed_as/1) to force ecto to use the `dump/1` function of custom type resulting in the correct `{"price": 123}` json object stored in the database.

The implementation is fairly straightforward:

```elixir
# lib/money/ecto/amount_type.ex
  def embed_as(_), do: :dump
```

`embed_as/1` callback was [added in ecto 3.2.0](https://github.com/elixir-ecto/ecto/blob/v3.3.2/CHANGELOG.md#v320-2019-09-07), but it can be added without causing backwards compatibility issues - it will simply not be called by ecto versions prior to 3.2.0

**Comment by Nitrino** [comment]
@teamon Thank you for investigating this issue.
We will be happy to pull requests if you want, 
Otherwise, I’ll do it myself in the coming days.
