### ISSUE TITLE
Money.equals? should not raise on different currencies

### ISSUE THREAD

**Issue by michelboaventura** [elixirmoney/money#127]
Hi,

I understand a call to ``fail_currencies_must_be_equal`` when trying to ``add``, ``subtract`` or ``compare`` two ``Money`` structs, but I think ``equals?`` should just returns ``false`` because there is nothing wrong with comparing USD with CAD, they are just different. Everytime I need to compare two ``Money``'s I need to do something like ``money1.currency == money2.currency && Money.equals?(money1, money2)``.

What do you think?

Thanks

**Comment by Nitrino** [comment]
Hi @michelboaventura,
I agree with you, `Money.equals?/2` should always return a boolean value.
I will fix this in the next release.
Or if you wish, you can send PR.

**Comment by michelboaventura** [comment]
Hi @Nitrino, I've just did it, thanks!

**Comment by Nitrino** [comment]
Merged #128
