### ISSUE TITLE
Money.new with integer

### ISSUE THREAD

**Issue by michelboaventura** [elixirmoney/money#129]
Hi,

Is there a special reason for ``Money.new/3`` only accept ``float()`` and ``binary()`` as first argument? I'm working with an api which returns me some prices but when the value doesn't have decimal places they just return an integer (don't ask me why). So I can get ``1.23`` or ``1`` from the same endpoint.

Passing this to ``Money.new`` raises when the value is an integer, so I had to do the following code, which isn't a big deal, but ain't pretty either.
```Elixir
Money.new(value / 1, "USD")
```
What do you think about changing it to also accept an integer?

Thanks

**Comment by Nitrino** [comment]
Hi @michelboaventura 
I think you mix up `Money.new` with `Money.parse`, right?
`Money.new` accept the only integer. 
`Money.parse` accept `float()` and `binary()`

I do not know the reasons for this logic. 
I think `Money.parse` should accept all possible amount types

**Comment by michelboaventura** [comment]
Hi @Nitrino, yes I mixed them up, thanks for understand and point it out. I will make a PR adding the option to also parse integers.

Thanks

**Comment by Nitrino** [comment]
@michelboaventura Merged. 
Thank you for your contribution!
