### ISSUE TITLE
Return atoms from compare instead of -1/0/1

### ISSUE THREAD

**Issue by niknetniko** [elixirmoney/money#137]
For example, [`DateTime.compare/2`](https://hexdocs.pm/elixir/DateTime.html#compare/2) returns `:lt`, `:eq` or `:gt`. This seams more readable than returning -1/0/1.

I'm willing to make a PR for this change, but since this breaks compatibility, it will probably require version 2.0, so I'm making this issue first to see if there is any interest in such a PR.

**Comment by Nitrino** [comment]
Hi @niknetniko 
I think we can add `Money.cmp` by analogy with `Decimal.cmp` and `Decimal.compare`.
So we won’t break backward compatibility

**Comment by niknetniko** [comment]
That's a good solution, I'll make a PR.
