### ISSUE TITLE
Wrong Format when you show symbol in a Negative amount

### ISSUE THREAD

**Issue by papakay** [elixirmoney/money#154]
`Money.new(-42000) |> Money.to_string(symbol: true)` gives

**₦-420**

but the most appropriate format should be

**-₦420**

Please how can this be resolved?

**Comment by wingyplus** [comment]
As I know, the library support only symbol prefix and suffix. No support symbol between sign and number. The solution might be write to_string manually (might be fork this function https://github.com/elixirmoney/money/blob/master/lib/money.ex#L559).

**Comment by Nitrino** [comment]
Hi guys.
I think this is a bug.
I will fix it as soon as there is time or I will be glad to pull requests

**Comment by wingyplus** [comment]
Do you have any reference about symbol position?

**Comment by Nitrino** [comment]
@wingyplus 
I don't know about the official specification, but seems format `-10$` used everywhere

**Comment by wingyplus** [comment]
I see. How about space position, should we add before or after symbol?

**Comment by darraghenright** [comment]
Hi there. I just came across this issue — formatting USD values; e.g:

```elixir
Money.parse!(-1, :USD) |> Money.to_string()
```
This yields `$-1.00` where I would expect `-$1.00`.

Happy to assist if there's anything I can do to help resolve this?
