### ISSUE TITLE
Dynamically adding currency

### ISSUE THREAD

**Issue by ErinHivelociy** [elixirmoney/money#165]
We are trying to use this in an application with custom currencies (point systems) and noticed if we would like to add a currency this requires adding to the config
```elixir
config :money,
  custom_currencies: [
    BTC: %{name: "Bitcoin", symbol: "₿", exponent: 8},
    GCS: %{name: "Galactic Credit Standard", symbol: "gcs", exponent: 0}
  ]
```
Would be great if we could add currencies dynamically for example: 
```elixir
Money.Currency.add({BTC: %{name: "Bitcoin", symbol: "₿", exponent: 8})
```
Willing to help contribute with a PR if there is interest from package owners. Was thinking of using an :ets table to handle the currency definitions backed by a GenServer (for example). 
The biggest issue with this will be handling the dynamically created methods
`Money.Currency.#{currency}(100)`
Will need to find a way to maintain this behavior. 🤔

**Comment by stevedomin** [comment]
Hi @ErinHivelociy! Is there a way to do this in the library currently? If not, any reason why it was closed and would it still fit in the lib?
