### ISSUE TITLE
Truncate/Human readable option?

### ISSUE THREAD

**Issue by pdgonzalez872** [elixirmoney/money#172]
Hi! Thanks for the library! It's awesome!

We had a use case the other day where we wanted to truncate (make it easier to read) a currency value:

```
$1,234,567 -> $1.2 m
```

I was wondering how folks usually tackle this problem. Do you have any suggestions? If this is a desirable feature, would you accept PRs?

Thank you!

**Comment by Nitrino** [comment]
I think in future versions we will add support for [CLDR Number and currency patterns](https://cldr.unicode.org/translation/number-currency-formats/number-and-currency-patterns)
