### ISSUE TITLE
Incorrect currency Symbols

### ISSUE THREAD

**Issue by kevinkirkup** [elixirmoney/money#184]
The symbols for Canadian and Singaporean dollar are incorrect.

Should be `Can$` and `S$` respectively.

[Language Navigator – Canadian dollar (symbol) (Linguistic](https://www.noslangues-ourlanguages.gc.ca/en/writing-tips-plus/canadian-dollar-symbol) 
[Canadian dollar](https://en.wikipedia.org/wiki/Canadian_dollar) 
[Singapore dollar](https://en.wikipedia.org/wiki/Singapore_dollar)

**Comment by Nitrino** [comment]
@mtrudel Thank you for the feedback. I double-checked and I agree it's a mistake. I will check all currencies and fix this shortly

**Comment by mtrudel** [comment]
Thanks for the response! 

Now that I'm using Money more deeply, it seems like a possibly useful distinction to make would be for different formatting behaviours for 'casual' (or perhaps its 'default') use. For example, if i'm working in a context where I'm *always* (or even almost always) going to be working with a single currency (like an informal budgeting app, for example), I may well use a more colloquial terminology than if I were working in a context where every value I see is in a different currency (like at a currency exchange house, for example). By way of example, in the first case every Canadian I know would simply use `$`, but in the latter case I'd see a lot more reasoning for `$123 CAD` (in this case I'd probably want to see this on *every* currency as well).

**Comment by Nitrino** [comment]
@mtrudel that makes sense, we can get this behavior by passing the `code: true` parameter.
```elixir
iex(6)> Money.to_string(Money.new(1_234_56, :CAD),  symbol: true, code: true)
"Can$1,234.56 CAD"
```
After fixing the symbol, it would look like your example. I plan to update all currency symbols according to ISO 4217 and check the edge cases

**Comment by mtrudel** [comment]
>  we can get this behavior by passing the code: true parameter.

Yes of course, that's right. I was getting tripped up because I was going out of my way to try and fix the `Can` part. Agree that once that's resolved the ergonomics are perfect.

Thanks again for a great library! It's amazing how much of the overall task of working with money is just magically taken care of with this.

**Comment by Nitrino** [comment]
During currency checking I recalled that this is not a trivial task. Some currencies have several symbols that are used, certain currencies may have a symbol in the front and others in the back, also it may depend on the localization. I hope I don't make it worse now. After [this PR](https://github.com/elixirmoney/money/pull/241) I plan to add the following features:
1. Alternative currency symbols
2. Simplify changing currencies
3. Add currency output format
4. Add formatting localization

**Comment by Nitrino** [comment]
@mtrudel During currency checking I recalled that this is not a trivial task. Some currencies have several symbols that are used, certain currencies may have a symbol in the front and others in the back, also it may depend on the localization. I hope I don't make it worse now. After [this PR](https://github.com/elixirmoney/money/pull/241) I plan to add the following features:
1. Alternative currency symbols
2. Simplify changing currencies
3. Add currency output format
4. Add formatting localization
