### ISSUE TITLE
Question - Change decimal precision

### ISSUE THREAD

**Issue by Macorreag** [elixirmoney/money#189]
I have checked the configuration of the Module and I cannot find a parameter that allows me to set a precision in the Module

```ex
  %Money{amount: 999999, currency: :COP}
  |> Money.to_string()
``` 
This returns me :
`"$9.999,99"`

It is possible to set it to take a precision of 3 decimal places and the result is something like.

`"$9.99,999"`

**Comment by Nitrino** [comment]
Hi @Macorreag 
Each currency has its own exponent, on the basis of which calculations and formulas are carried out.
https://github.com/elixirmoney/money/blob/master/lib/money/currency.ex#L64

If you need a currency with a different exponent, then you can declare a custom currency
https://github.com/elixirmoney/money#custom-currencies

**Comment by Macorreag** [comment]
Thanks @Nitrino  for the quick response.
