### ISSUE TITLE
Breaking change between 1.11 and 1.12

### ISSUE THREAD

**Issue by michelboaventura** [elixirmoney/money#198]
Hi! I've found a breaking change between 1.11 to 1.12:

```Elixir
# 1.11
Money.parse!("6.0e3", "USD") == %Money{amount: 603, currency: :USD}

# 1.12
Money.parse!("6.0e3", "USD") == %Money{amount: 600000, currency: :USD}
```

So in 1.11 the `e` was completely ignored and now it's properly handled, which yields completely different values for the same input.

So maybe we should add a breaking change on the release logs so that other users can be prepared.

Thanks!

**Comment by Nitrino** [comment]
Hi @michelboaventura thanks for your report. 
I think you are right. I will retire this version and release a new one without this feature

**Comment by Nitrino** [comment]
New v1.12.1 released. Thank you for your attention

**Comment by michelboaventura** [comment]
Thank you for the great lib!
