### ISSUE TITLE
Money.parse return :error

### ISSUE THREAD

**Issue by vuvantoan95** [elixirmoney/money#202]
according to the docs
![Screenshot 2023-04-04 at 11 33 54](https://user-images.githubusercontent.com/16610569/229687849-ba17e8ae-4f59-4836-b3b8-c93adc3d57e6.png)

but when I run it in project install [{:money, "~> 1.12"}], I get this error
![Screenshot 2023-04-04 at 11 33 03](https://user-images.githubusercontent.com/16610569/229687793-43aa3595-ae5b-4b81-b6eb-35af927ef24f.png)

 Elixir (1.7.4)
decimal 1.9.0
Pls help!

**Comment by Nitrino** [comment]
@vuvantoan95 Hi, issue solved?
