### ISSUE TITLE
Ecto aggregate functions sometimes return Decimal.

### ISSUE THREAD

**Issue by aglassman** [elixirmoney/money#219]
**Problem**
I modified a table's 'amount_in_cents' column to be the PostgreSQL type `bigint` rather than `integer`.  This seems to have caused calls using Repo.aggregate calls to fail to load the result type into a Money struct.

```
schema "adjustments" do
  field :amount_in_cents, Money.Ecto.Amount.Type
  # ...
end


#

query = from(a in Adjustment, where a.wallet_id == ^wallet_id)
Repo.aggregate(query, :sum, :amount_in_cents)
```
This results in the following issue.

![Screenshot 2024-05-14 at 1 00 57 PM](https://github.com/elixirmoney/money/assets/1435196/5906b545-c181-4526-8c90-3ba1b68c445d)

I'm not totally sure why aggregate changes it's return type from an integer to a Decimal.
This causes `Money.Ecto.Amount.Type.load/1` to fail to match.

**Proposed Solution**
Add a new function head to the load function.
```
@spec load(integer()) :: {:ok, Money.t()}
    def load(int) when is_integer(int), do: {:ok, Money.new(int)}
    def load(%Decimal{} = decimal), do: Money.parse(decimal) 
```

**Comment by Nitrino** [comment]
Thanks for the description and solution!
