### ISSUE TITLE
premix.exs. Reason: enoent

### ISSUE THREAD

**Issue by paridin** [elixirmoney/money#228]
The latest version 0.13.0 gives me the error `../deps/money/blend/premix.exs. Reason: enoent`.

**Comment by heywhy** [comment]
I'm thinking it's a leftover. I hope they fix it ASAP.

**Comment by heywhy** [comment]
this particular [change](https://github.com/elixirmoney/money/commit/51ee08914675325c4fe25413730fa74d94f37548#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308R1) led to this issue

**Comment by tekpriest** [comment]
installing old version `1.12.0` has been marked as retired

**Comment by grzuy** [comment]
> Yes, it's missing from the release, it should be added via `package/1` at mix file adding the `files` attribute to the keyword list.

blend is a dev-only tool, not intended for the release.

https://github.com/elixirmoney/money/pull/229

**Comment by Nitrino** [comment]
Hi all. 
I've released v1.13.1 and v1.13.0 has been retired. 
Thank you @grzuy for fix!
