### ISSUE TITLE
Compatibility issue with Ecto 3.12.0

### ISSUE THREAD

**Issue by krns** [elixirmoney/money#231]
I'm working with money 1.12.4. After upgrading Ecto from 3.11.2 to 3.12.0 my tests show the following errors:

```
  2) stake test...
     test/my_app/module.exs:47
     Assertion with == failed
     code:  assert stake.distribution_amount == %Money{amount: 1000, currency: :EUR}
     left:  1000
     right: %Money{amount: 1000, currency: :EUR}
```

Could this be caused by the internal representation of parameterized types (see https://hexdocs.pm/ecto/changelog.html#potential-incompatibilities)?

**Comment by Nitrino** [comment]
Hi @krns. 
Can you provide more information about what `stake.distribution_amount` is and how you create it? I need a way to reproduce this

**Comment by krns** [comment]
Never mind, I've just realised that we have our own layer of abstraction in front of 'money'. I will investigate further and get back to you if in doubt.... Sorry for the noise.
