### ISSUE TITLE
Support for multiple currencies (Ecto)?

### ISSUE THREAD

**Issue by nicohvi** [elixirmoney/money#30]
Hi, love the library - great work! 👍 

In the docs it says

```
This type expects you to use a single currency. The currency must be defined in your configuration.
```

Any plans on making it support multiple? Or would you perhaps be interested in a pull request?

Cheers

**Comment by liuggio** [comment]
ops the topic was about Ecto ... :)

**Comment by nicohvi** [comment]
I'll take a look @andrewtimberlake 👍

**Comment by cesarizu** [comment]
I've tested this and it works really well.

**Comment by wojtekmach** [comment]
@andrewtimberlake I created a similar library for educational purposes and for multiple currencies I've used composite type that Ecto supports seamlessly - you might consider that as well. Although it may work just for some SQL DBs (or just Postgres). https://github.com/wojtekmach/acme_bank/blob/master/apps/money/lib/money/ecto.ex

**Comment by andrewtimberlake** [comment]
Thanks @wojtekmach that is helpful. I’m pretty sure that will limit the database adapters that can be supported.
Perhaps I can look into two Ecto types if there are performance benefits for custom database types.

**Comment by vraravam** [comment]
@andrewtimberlake - have you progressed beyond the idea stage? I would like to try and use it in my project.

**Comment by jordi-adame** [comment]
https://github.com/liuggio/money/pull/61

**Comment by Schultzer** [comment]
@jordi-adame How does #60 fix the problem with multiple currencies?

@Nitrino Is there any plan to fix this issue where [Money](https://github.com/liuggio/money/) only takes a specific currency, where you have to set it in config, it should be more flexible in my use case I need to use several different currencies in the same repo.


when default is set to :USD 
```elixer
import Money

Repo.insert(%Price{amount: Money.new(10000, :USD) -> %Money{amount: 10000, currency: :USD}
Repo.insert(%Price{amount: Money.new(10000, :THB) -> %Money{amount: 10000, currency: :USD}
Repo.insert(%Price{amount: Money.new(10000, :DKK) -> %Money{amount: 10000, currency: :USD}
```

**Comment by Nitrino** [comment]
@Schultzer You are right, #60 does not fix this problem.
I also suffer from this problem in my project. This is the first task of which I'm doing now.

**Comment by Schultzer** [comment]
@Nitrino I'm just letting you know that I found a more promising module at https://github.com/kipcole9/money
maybe you can get some inspiration there.

**Comment by ryanwinchester** [comment]
Not being able to save in different currencies kind of makes the whole thing pointless. If I only had to deal with one currency, I don't need a money library 😕

**Comment by Nitrino** [comment]
Added in v1.4.0
https://github.com/elixirmoney/money/blob/master/CHANGELOG.md#140
