### ISSUE TITLE
Custom currencies

### ISSUE THREAD

**Issue by ramontayag** [elixirmoney/money#52]
What do you suggest we do for custom currencies, like cryptocurrencies?

**Comment by andrewtimberlake** [comment]
I’ll have a think on this

**Comment by geonnave** [comment]
Hi, just to log my interest, I've come to need custom cryptocurrency support too :)

**Comment by Nitrino** [comment]
Related with #84 
This feature includes a list for implementation in the near future.

**Comment by Nitrino** [comment]
Custom currencies added in v1.5.
