### ISSUE TITLE
division by float

### ISSUE THREAD

**Issue by namxam** [elixirmoney/money#83]
Is there a reason why division are only supported by integers? If not, I would try to fix it and submit a pull request.

**Comment by andrewtimberlake** [comment]
Division of money returns an array of equal amounts with one holding the remainder.
```elixir
iex> Money.divide(Money.new(9, :USD), 4)
[
  %Money{amount: 3, currency: :USD},
  %Money{amount: 2, currency: :USD},
  %Money{amount: 2, currency: :USD},
  %Money{amount: 2, currency: :USD}
]
```
How do you propose `Money.divide(Money.t, float)` would work?

**Comment by andrewtimberlake** [comment]
When you work with money, the literal stuff, how do you divide it?

When you add money, you take two amounts and you have a new amount
When you subtract money, you remove an amount and you are left with a new amount
When you invest and multiply your money, you increase it and are left with a new amount
But when you divide your money up, you are left with multiple amounts.

**Comment by namxam** [comment]
Yeah, but actually isn't it the case for any value? It just feels really unnatural. I probably would have gone with a different verb … like `split`. I am not a native speaker, but I think you also say _split a bill_ and not _divide a bill_.

**Comment by jnmandal** [comment]
For what its worth we had a similar discussion in my company. We use the `divide` function as a split, and we were surprised to see that it supported the use case of dividing by a negative amount.

**Comment by BobbieBarker** [comment]
What about calculating percentages with division?

**Comment by theguuholi** [comment]
I am going to try to implement this feature.
