### ISSUE TITLE
Sync currency definitions from ISO source?

### ISSUE THREAD

**Issue by saverio-kantox** [elixirmoney/money#84]
Here https://www.currency-iso.org/dam/downloads/lists/list_one.xml you can retrieve the most correct definitions for currencies (symbols, exponent etc). Maybe a script that converts that into elixir code would be nice?

Something like in this package https://hex.pm/packages/string_naming is done to convert the unicode source file into actual modules - but greatly simplified?

I would have a run to a PR if you agree.

**Comment by Nitrino** [comment]
Hi @saverio-kantox, 
Sorry for long response.

I fully agree, the list of currencies must match with ISO list.
But it seems we should have our own list with the ability to customize and add currencies.

For example, we still need to keep a list of characters or add support for cryptocurrencies.
We are open to pull requests if you wish.

**Comment by Nitrino** [comment]
At the moment, it seems we are compatible with ISO.
And custom currencies added in v1.5.
