### ISSUE TITLE
Warn/raise when the currency passed in is not the currency in the config

### ISSUE THREAD

**Issue by pdgonzalez872** [elixirmoney/money#98]
Hi!

Thanks for the work here! Following up on the discussion on this [PR](https://github.com/liuggio/money/pull/96), we observed a non-critical issue when dealing with different currencies other than the one specified in the config file.

Ex:

```# Copy/paste from @Nitrino 
config :money,
  default_currency: :GDP,

iex(2)> Type.cast("R$ 1.234,00")
{:ok, %Money{amount: 123, currency: :GBP}}
```

I think the behavior here should to at least warn the user about the mismatch as opposed to converting the amount incorrectly and silently.

Please let me know if you agree with this. If not, no worries, please close this issue! If you do agree, I'd like to take a stab at it if possible.

Thanks for the work!

**Comment by Nitrino** [comment]
Fixing this is not difficult. 
But I will be happy to help sort out the library and attract new contributors.

**Comment by Nitrino** [comment]
Hi @pdgonzalez872 
I completely agree that in these cases, the cast should return an error
Fixing this is not difficult.
But I will be happy to help sort out the library and attract new contributors.
I'll be waiting for your PR.

**Comment by Nitrino** [comment]
Since there was no response for several days, the issue was fixed.

**Comment by pdgonzalez872** [comment]
@Nitrino completely understand, no worries! Sorry, things got a little busy for me in the last few days. Thanks for solving this issue!
